/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package it.gov.pagopa.onboarding.workflow.controller.web;


import it.gov.pagopa.onboarding.workflow.dto.web.InitiativeWebDTO;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;



/**
 * IdPay - Citizen Onboarding - Web
 */

@RestController
@RequestMapping("/idpay/onboarding/web")
public interface OnboardingControllerWeb {


  /**
   * Returns the initiative details
   *
   * @param initiativeId
   * @return
   */
  @GetMapping("/{initiativeId}/detail")
  ResponseEntity<InitiativeWebDTO> getInitiativeWeb(
          @PathVariable("initiativeId") String initiativeId);


}