apiVersion: v2
name: idpay-onboarding-workflow
description: Onboarding Workflow for IdPay
type: application
version: latest
appVersion: latest
dependencies:
  - name: microservice-chart
    version: 1.17.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"