/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package it.gov.pagopa.onboarding.workflow.controller;

import it.gov.pagopa.onboarding.workflow.dto.*;
import it.gov.pagopa.onboarding.workflow.dto.web.InitiativeWebDTO;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Locale;

/**
 * IdPay - Citizen Onboarding
 */

@RestController
@RequestMapping("/idpay/onboarding")
public interface OnboardingController {

    /**
     * Returns the initiative details
     *
     * @param initiativeId
     * @RequestHeader acceptLanguage
     * @return
     */
    @GetMapping("/{initiativeId}/detail")
    ResponseEntity<InitiativeWebDTO> getInitiativeDetail(
            @PathVariable("initiativeId") String initiativeId,
            @RequestHeader(value = "Accept-Language", defaultValue = "it_IT") Locale acceptLanguage);

    /**
     * Returns the actual onboarding status
     *
     * @param initiativeId
     * @param userId
     * @return
     */
    @GetMapping("/{initiativeId}/{userId}/status")
    ResponseEntity<OnboardingStatusDTO> onboardingStatus(
            @PathVariable("initiativeId") String initiativeId, @PathVariable("userId") String userId);

    /**
     * Save the consents of PDND criteria and Self declaration list
     *
     * @param consentPutDTO
     * @param userId
     * @return
     */
    @PutMapping("/{userId}")
    ResponseEntity<Void> saveOnboarding(
            @RequestBody ConsentPutDTO consentPutDTO,
            @RequestHeader ("X-Client-Channel") String channel,
            @PathVariable("userId") String userId);

    // Servizi non utilizzati nel workflow di IO o WEB

    @GetMapping("/user/{userId}/initiative/status")
    public ResponseEntity<List<OnboardingStatusCitizenDTO>> onboardingStatusList(
            @PathVariable("userId") String userId,
            @RequestHeader(name = "Accept-Language", required = false, defaultValue = "it-IT") String acceptLanguage);
    /**
     * Deactivation onboarding
     *
     * @param body
     * @return
     */
    @DeleteMapping("/disable")
    ResponseEntity<Void> disableOnboarding(
            @Valid @RequestBody UnsubscribeBodyDTO body);

    /**
     * rollback onboarding
     *
     * @param initiativeId
     * @param userId
     * @return
     */
    @PutMapping("/rollback/{initiativeId}/{userId}")
    ResponseEntity<Void> rollback(
            @PathVariable("initiativeId") String initiativeId, @PathVariable("userId") String userId,
            @RequestParam(value = "updateFamilyMember", required = false, defaultValue = "true") Boolean updateFamilyMembers);

    @PutMapping("/{initiativeId}/{userId}/suspend")
    ResponseEntity<Void> suspend(@PathVariable("initiativeId") String initiativeId, @PathVariable("userId") String userId);

    @PutMapping("/{initiativeId}/{userId}/readmit")
    ResponseEntity<Void> readmit(@PathVariable("initiativeId") String initiativeId, @PathVariable("userId") String userId);

    @GetMapping("/{initiativeId}/{userId}/family")
    ResponseEntity<OnboardingFamilyDTO> familyUnitComposition(
            @PathVariable("initiativeId") String initiativeId, @PathVariable("userId") String userId);
}
